const events = [
  {
    datum1: 'vrijdag 11 oktober',
    dag: 'VR',
    nummerMaand: '11 okt',
    naam: 'LOVE IS ALL',
    stad: 'Breda',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 11 oktober',
    dag: 'VR',
    nummerMaand: '11 okt',
    naam: 'Techno Night',
    stad: 'Utrecht',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 11 oktober',
    dag: 'VR',
    nummerMaand: '11 okt',
    naam: 'Pop Up Jazz',
    stad: 'Rotterdam',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 12 oktober',
    dag: 'ZA',
    nummerMaand: '12 okt',
    naam: 'The Underground Soul Train - Invites David Dam',
    stad: 'Oosterhout',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 12 oktober',
    dag: 'ZA',
    nummerMaand: '12 okt',
    naam: 'LEGENDS of ROCK Tribute Festival',
    stad: 'Enschede',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 12 oktober',
    dag: 'ZA',
    nummerMaand: '12 okt',
    naam: 'House Music Madness',
    stad: 'Amsterdam',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 12 oktober',
    dag: 'ZA',
    nummerMaand: '12 okt',
    naam: 'Festival of Lights',
    stad: 'Den Haag',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 19 oktober',
    dag: 'ZA',
    nummerMaand: '19 okt',
    naam: 'Disco Fever met o.a. NPO radio dj Corné Klijn',
    stad: 'Zwolle',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 19 oktober',
    dag: 'ZA',
    nummerMaand: '19 okt',
    naam: 'Latin Dance Party',
    stad: 'Rotterdam',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 25 oktober',
    dag: 'VR',
    nummerMaand: '25 okt',
    naam: 'LEGENDS of ROCK Tribute Tour De Vorstin Hilversum',
    stad: 'Hilversum',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 25 oktober',
    dag: 'VR',
    nummerMaand: '25 okt',
    naam: 'Jazz Night',
    stad: 'Groningen',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 9 november',
    dag: 'ZA',
    nummerMaand: '9 nov',
    naam: 'Latin Live',
    stad: 'Breda',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 9 november',
    dag: 'ZA',
    nummerMaand: '9 nov',
    naam: 'Rock the City',
    stad: 'Eindhoven',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 16 november',
    dag: 'ZA',
    nummerMaand: '16 nov',
    naam: 'Vroeg Feest Zwolle',
    stad: 'Zwolle',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 16 november',
    dag: 'ZA',
    nummerMaand: '16 nov',
    naam: 'Hip Hop Legends',
    stad: 'Maastricht',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 23 november',
    dag: 'ZA',
    nummerMaand: '23 nov',
    naam: 'LEGENDS of ROCK Tribute Festival XL Bonte Wever',
    stad: 'Assen',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 29 november',
    dag: 'VR',
    nummerMaand: '29 nov',
    naam: 'LEGENDS of ROCK Tribute Tour in Gebouw-T',
    stad: 'Bergen op Zoom',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 29 november',
    dag: 'VR',
    nummerMaand: '29 nov',
    naam: 'Reggae Night',
    stad: 'Tilburg',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 30 november',
    dag: 'ZA',
    nummerMaand: '30 nov',
    naam: 'LEGENDS of ROCK Tribute Festival XXL in AHOY',
    stad: 'Rotterdam',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 30 november',
    dag: 'ZA',
    nummerMaand: '30 nov',
    naam: 'Winter Wonderland Dance',
    stad: 'Amsterdam',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'donderdag 12 december',
    dag: 'DO',
    nummerMaand: '12 dec',
    naam: 'De Kerstpakketmarkt',
    stad: 'Breda',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'donderdag 12 december',
    dag: 'DO',
    nummerMaand: '12 dec',
    naam: 'Christmas Jazz',
    stad: 'Leiden',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 13 december',
    dag: 'VR',
    nummerMaand: '13 dec',
    naam: 'MOOON',
    stad: 'Tilburg',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'vrijdag 13 december',
    dag: 'VR',
    nummerMaand: '13 dec',
    naam: 'Funky Friday',
    stad: 'Arnhem',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 14 december',
    dag: 'ZA',
    nummerMaand: '14 dec',
    naam: 'Eclipse',
    stad: 'Nijmegen',
    flyer: '/images/7fest2022.jpg',
    link: 'https://www.youtube.com',
  },
  {
    datum1: 'zaterdag 14 december',
    dag: 'ZA',
    nummerMaand: '14 dec',
    naam: 'Saturday Night Fever',
    stad: 'Breda',
    flyer: '/images/csc.jpg',
    link: 'https://www.youtube.com',
  },
];

export default events;
